### ISSUE TITLE
Invalid Arguments Exception

### ISSUE THREAD

**Issue by abo-github** [WaveEngine/UIWindowSystemsDemo#1]
Launching the demo with Visual Studio 2019 throws me exception:

```
SharpDX.SharpDXException
  HResult=0x80070057
  Nachricht = HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Falscher Parameter.

  Quelle = SharpDX
  Stapelüberwachung:
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description)
   at WaveEngine.DirectX11.DX11Texture.NewTexture2D(DataBox[] data, TextureDescription description, Device device)
   at WaveEngine.DirectX11.DX11Texture..ctor(DX11GraphicsContext context, DataBox[] data, TextureDescription& description, SamplerStateDescription& samplerState)
   at WaveEngine.DirectX11.DX11ResourceFactory.CreateTextureInternal(DataBox[] data, TextureDescription& description, SamplerStateDescription& samplerState)
   at WaveEngine.Common.Graphics.ResourceFactory.CreateTexture(DataBox[] data, TextureDescription& description, SamplerStateDescription& samplerState, String debugName)
   at WaveEngine.Common.Graphics.ResourceFactory.CreateTexture(TextureDescription& description, String debugName)
   at WaveEngine.Components.Environment.AtmosphereController.ComputeAtmosphereTextureUpdater.Initialize()
   at WaveEngine.Components.Environment.AtmosphereController.OnAttached()
   at WaveEngine.Framework.AttachableObject.Attach()
   at WaveEngine.Framework.Entity.OnAttached()
   at WaveEngine.Framework.AttachableObject.Attach()
   at WaveEngine.Framework.Managers.EntityManager.InternalActivateEntity(Entity entity)
   at WaveEngine.Framework.Managers.EntityManager.OnActivated()
   at WaveEngine.Framework.AttachableObject.Activate()
   at WaveEngine.Framework.Managers.SceneManagers.ActivateManagers()
   at WaveEngine.Framework.Scene.Initialize()
   at WaveEngine.Framework.Services.ScreenContextManager.InitializeASingleScene(Scene scene)
   at WaveEngine.Framework.Services.ScreenContextManager.InitializeScreenContext(ScreenContext context)
   at WaveEngine.Framework.Services.ScreenContextManager.ToExecute(ScreenContext nextContext, ScreenTransition transition, Boolean doDispose)
   at WaveEngine.Framework.ScreenContextCommands.ToContextCommand.Execute()
   at WaveEngine.Framework.Services.ScreenContextManager.Update(TimeSpan gameTime)
   at WaveEngine.Framework.Application.UpdateFrame(TimeSpan gameTime)
   at UIWindowSystemsDemo.WPF.App.<>c__DisplayClass4_0.<OnStartup>b__1() in C:\Users\Arthur\Downloads\UIWindowSystemsDemo-1.0.1\UIWindowSystemsDemo.WPF\App.xaml.cs:line 44
   at WaveEngine.WPF.WPFWindowsSystem.CompositionTarget_Rendering(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

  Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:
    [Externer Code]
    UIWindowSystemsDemo.WPF.App.OnStartup.AnonymousMethod__1() in App.xaml.cs
    [Externer Code]
```

UIWindowSystemDemo.WPF / App.xaml.cs / Line 44 "WaveApplication.UpdateFrame(**gameTime**)

Although the datatype is right (System.Timespan). In my case, in debug mode it had the value {00:00:01.9385902}

**Comment by danielcaceresm** [comment]
Hi @abo-github,

Sorry for not replying before but we do not watch this repository issues. If you still have problems, you can create an issue in https://github.com/WaveEngine/Documentation.

I will deactivate the issues tab in this repository.

Greetings
